<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.4.12" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.6.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.13" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.95.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Languages\HotkeyBoxStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HotkeyBoxStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="Overlay\Confirmation\MessageDialogView.axaml.cs">
      <DependentUpon>ConfirmationDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Account\Views\AccountsPageView.axaml.cs">
      <DependentUpon>AccountsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Region\Views\RegionsPageView.axaml.cs">
      <DependentUpon>RegionsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Region\Views\EditRegionFormView.axaml.cs">
      <DependentUpon>EditRegionFormView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instance\Views\EditInstanceFormView.axaml.cs">
      <DependentUpon>EditInstanceFormView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instance\Views\InstancesPageView.axaml.cs">
      <DependentUpon>InstancesPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Logs\LogsPageView.axaml.cs">
      <DependentUpon>LogsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="GlobalSettings\GlobalSettingsPageView.axaml.cs">
      <DependentUpon>GlobalSettingsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MainWindow\MainWindowView.axaml.cs">
      <DependentUpon>MainWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="InitialWindowView.axaml.cs">
      <DependentUpon>InitialWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Card\Views\AddCard.axaml.cs">
      <DependentUpon>AddCard.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Card\Views\Card.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>Card.axaml</DependentUpon>
    </Compile>
    <Compile Update="Card\Views\EditableCard.axaml.cs">
      <DependentUpon>EditableCard.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Overlay\Message\ConfirmDelete\Region\ConfirmDeleteRegionDialogView.axaml.cs">
      <DependentUpon>ConfirmDeleteRegionDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\Dialog.axaml.cs">
      <DependentUpon>Message.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Account\Views\DeleteAccountDialogView.axaml.cs">
      <DependentUpon>DeleteAccountDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instance\Views\DeleteInstanceDialogView.axaml.cs">
      <DependentUpon>DeleteInstanceDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Region\Views\DeleteRegionDialogView.axaml.cs">
      <DependentUpon>DeleteRegionDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Remove="Common\Converters\CollectionIsNotEmptyConverter.cs" />
    <Compile Update="Overlay\Dialog\StopInstances\StopInstancesDialogView.axaml.cs">
      <DependentUpon>StopInstancesDialogView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instance\Views\EditInstanceFormView.Design.cs">
      <DependentUpon>EditInstanceFormView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Languages\Validation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Validation.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Languages\HotkeyBoxStrings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>HotkeyBoxStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Languages\Validation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Validation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
